[WIP] GALAH
MultimodalUniverse/MultimodalUniverse pull request #24
Opened 2024-03-26 21:32 UTC by maja-jablonska

2024-03-27 19:05 UTC, maja-jablonska commented
I'd say it's almost done, I'm just not sure how to process resolution. I asked at ANU.

2024-03-28 19:45 UTC, maja-jablonska commented
I'm thinking of providing some util functions, e.g. to extract the spectra fluxes corresponding to three arms of the spectrograph - it might be a bit confusing to see a combined dataset like this.

![image](https://github.com/AstroPile/AstroPile_prototype/assets/23705704/45856cbb-922f-4a60-a384-7ad0291e0732)

2024-03-29 16:01 UTC, maja-jablonska commented
Added filter indices so that it can be viewed per-arm!

![image](https://github.com/AstroPile/AstroPile_prototype/assets/23705704/3d78e27f-8e64-4432-917c-0cd8daa85cc2)

2024-11-12 16:23 UTC, mb010 requested changes
Can we remove the cached data from the ipython notebook cells?

2024-11-13 09:29 UTC, mb010 requested changes
@maja-jablonska if you have a chance to update the PR this week, that would be ideal. If not, let me know and I'll have a look.

2024-11-15 11:53 UTC, mb010 commented on scripts/galah/README.md
> +
```suggestion
The data can be loaded for example as follows:
```python
from datasets import load_dataset
import matplotlib.pyplot as plt

dataset = load_dataset('./galah.py', trust_remote_code=True, split='train')
spectrum = dataset['train'][0]['spectrum']
spectrum.keys()

filter_ = 'B'
s_ind, e_ind = dataset['train'][0]['filter_indices'][f'{filter_}_start'], dataset['train'][0]['filter_indices'][f'{filter_}_end']
plt.plot(spectrum['lambda'][s_ind:e_ind], spectrum['flux'][s_ind:e_ind], color='royalblue')
plt.xlabel(r'wavelength ($\AA$)')
plt.ylabel(r'flux (erg/s/cm$^2$/$\AA$)')
plt.title('Spectrum for Selected Star: B Filter')
```
```

2024-11-15 11:54 UTC, mb010 approved these changes
lgtm

2024-11-15 13:12 UTC, mb010 commented
GALAH completed fine. Apogee failed in the build test with the outdated configuration. Going forward with merge.

2024-11-15 13:12 UTC, merged