Adding Carnegie Supernova Project I Data Release 3
MultimodalUniverse/MultimodalUniverse pull request #52
Opened 2024-04-18 19:15 UTC by ado8

# Adds the Carnegie Supernova Project I Type Ia Supernova Data Release 3 to Astropile 
Collaboration with @tom-hehir @mb010 @erinhay @David-Chemaly @benboyd97 @mattgrayling and others.

Adding a multiband time-series dataset of Type Ia supernovae from CSP DR3. This code is largely based on the yse code in https://github.com/AstroPile/AstroPile_prototype/pull/46, except for the way data is loaded from files (SNooPy format vs SNANA format).

## Link for reference
[CSP Data](https://csp.obs.carnegiescience.edu/data)
- [Krisciunas et al., 2017](https://ui.adsabs.harvard.edu/abs/2017AJ....154..211K/abstract)
- [CSP DR3](https://csp.obs.carnegiescience.edu/data/CSP_Photometry_DR3.tgz)

## HuggingFace Dataset Format
Each example contains:

  - `object_id`: Dataset specific identifier
  - `spec_class`: Spectral class
  - `ra`, `dec`: right ascension, declination
  - `redshift`: redshift of target. : As decided by ordered availability of: `['REDSHIFT_FINAL', 'REDSHIFT_CMB', 'REDSHIFT_HELIO']`
  - `lightcurve`: object with:
                - `band`: band of observation, arr(string),
                - `time`: timestamp of observation in MJD, arr(float)
                - `mag`: Magnitude (CSP natural system) value of observation, arr(float),
                - `mag_err`: Magnitude (CSP natural system) uncertainty of observation, arr(float)

2024-04-19 15:34 UTC, ado8 commented
The Carnegie Supernova Project's [site](https://csp.obs.carnegiescience.edu) seems down at the moment (19/4/2024).
test.sh completed successfully before pushing, but now fails without any change in code.

2024-06-12 12:17 UTC, mb010 commented on download_data.py
> +def download_text_file(url, file_path):
```suggestion
import os

def download_text_file(url, file_path):
```

2024-06-12 12:21 UTC, mb010 commented on scripts/.DS_Store
This file should be removed.

2024-06-12 12:21 UTC, mb010 commented on download_data.py
> +def download_text_file(url, file_path):
```suggestion
import os

def download_text_file(url, file_path):
```

2024-06-12 12:23 UTC, mb010 commented on scripts/csp/csp.py
> +_HOMEPAGE = "https://csp.obs.carnegiescience.edu/data/CSP_Photometry_DR3.tgz"
Link to the science project rather than the data download.

2024-06-12 14:51 UTC, ado8 commented
I messed up my branches and put some CfA edits in during commit 63f6591 and 65ae8b4.
I don't usually work with branches, so I don't know how to scrub these or move them to the CfA branch.

Also, the root level download_data.py file looks like it was from a foundation branch I copied things from.
I don't think it should be there, so I deleted it in this branch.

2024-06-12 15:31 UTC, mb010 commented on scripts/csp/csp.py
> +_HOMEPAGE = "https://csp.obs.carnegiescience.edu/data/CSP_Photometry_DR3.tgz"
Fixed.

2024-06-12 15:35 UTC, mb010 requested changes
This uncovered more links to data rather than homepages. I think its fine otherwise. This is supposed to be an accessible review / contribution process, and your changes just make things better. 🙂 No worries on that front.

2024-06-12 15:35 UTC, mb010 commented on scripts/cfa/cfa_SECCSN.py
>  _HOMEPAGE = "https://lweb.cfa.harvard.edu/supernova/lc.standardsystem.sesn_allphot.dat"
This should be the homepage, not the data origin.

2024-06-12 15:35 UTC, mb010 commented on scripts/cfa/cfa4.py
>  _HOMEPAGE = "https://lweb.cfa.harvard.edu/supernova/CfA4/cfa4.lc.stdsystem.fi.ascii"
This should be the homepage, not the data origin.

2024-06-12 15:35 UTC, mb010 commented on scripts/cfa/cfa_SECCSN.py
> +_LICENSE = "CC BY-NC-SA 4.0"
This is confirmed?

2024-06-12 15:41 UTC, mb010 commented on scripts/cfa/cfa_SECCSN.py
>  _HOMEPAGE = "https://lweb.cfa.harvard.edu/supernova/lc.standardsystem.sesn_allphot.dat"
```suggestion
_HOMEPAGE = "https://lweb.cfa.harvard.edu/supernova/"
```

2024-06-12 19:20 UTC, EiffL commented
if you update from the main branch it should work

2024-10-08 19:24 UTC, mb010 approved these changes

2024-10-08 19:52 UTC, merged